---
apiVersion: v1
kind: Namespace
metadata:
  name: syslog
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-rsyslog
  namespace: syslog
  labels:
    app: rsyslog
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: rsyslog-udp
      port: 514
      targetPort: 514
      protocol: UDP
  selector:
    app: rsyslog 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
  namespace: syslog 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
        - containerPort: 111
          name: rpcbind
        - containerPort: 20048
          name: mountd
        - containerPort: 2049
          name: nfs
        volumeMounts:
        - mountPath: /exports 
          name: nfs-data
        securityContext:
          privileged: true 
      volumes:
      - name: nfs-data
        gcePersistentDisk:
          fsType: ext4
          pdName: b1-syslog-data-2 
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: syslog
  labels:
    app: nfs-server
spec:
  selector:
    app: nfs-server 
  ports:
  - name: nfs1
    port: 2049
    protocol: TCP
  - name: nfs2
    port: 20048
    protocol: TCP
  - name: nfs3
    port: 111
    protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  labels:
    app: rsyslog
  namespace: syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: garybowers/rsyslog:0.4
        ports:
        - containerPort: 514
          protocol: UDP
        volumeMounts:
        - mountPath: /var/log/remote
          name: logdata
      volumes:
      - name: logdata
        nfs:
          server: nfs-server.syslog.svc.cluster.local 
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: syslog
  labels:
    app: rsyslog
spec:
  selector:
    app: rsyslog
  ports:
  - name: syslog
    port: 514
    protocol: UDP 
