---
apiVersion: v1
kind: Namespace
metadata:
  name: rsyslog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  labels:
    app: rsyslog
  namespace: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: garybowers/rsyslog:0.1
        ports:
        - containerPort: 514
        volumeMounts:
        - mountPath: /var/log/remote
          name: logdata
      volumes:
      - name: logdata
        gcePersistentDisk:
          fsType: ext4
          pdName: b1-syslog-data 
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: rsyslog
  labels:
    app: rsyslog
spec:
  selector:
    app: rsyslog
  ports:
  - name: syslog
    port: 514
    protocol: TCP
